/*
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ProductUpdateAssetEntryPayload;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BulkUpdateAssetsEntriesRequestUpdateEntity
 */
public class BulkUpdateAssetsEntriesRequestUpdateEntityTest {
    private final BulkUpdateAssetsEntriesRequestUpdateEntity model = new BulkUpdateAssetsEntriesRequestUpdateEntity();

    /**
     * Model tests for BulkUpdateAssetsEntriesRequestUpdateEntity
     */
    @Test
    public void testBulkUpdateAssetsEntriesRequestUpdateEntity() {
        // TODO: test BulkUpdateAssetsEntriesRequestUpdateEntity
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'payload'
     */
    @Test
    public void payloadTest() {
        // TODO: test payload
    }

    /**
     * Test the property 'payloadMask'
     */
    @Test
    public void payloadMaskTest() {
        // TODO: test payloadMask
    }

}
