/*
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EntitymanagerGetAttributeOptionRequest
 */
public class EntitymanagerGetAttributeOptionRequestTest {
    private final EntitymanagerGetAttributeOptionRequest model = new EntitymanagerGetAttributeOptionRequest();

    /**
     * Model tests for EntitymanagerGetAttributeOptionRequest
     */
    @Test
    public void testEntitymanagerGetAttributeOptionRequest() {
        // TODO: test EntitymanagerGetAttributeOptionRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'listCode'
     */
    @Test
    public void listCodeTest() {
        // TODO: test listCode
    }

    /**
     * Test the property 'optionId'
     */
    @Test
    public void optionIdTest() {
        // TODO: test optionId
    }

}
