/*
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.EntitymanagerAttributeWriteErrors;
import org.openapitools.client.model.EntitymanagerEntity;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EntitymanagerCreateEntityResponse
 */
public class EntitymanagerCreateEntityResponseTest {
    private final EntitymanagerCreateEntityResponse model = new EntitymanagerCreateEntityResponse();

    /**
     * Model tests for EntitymanagerCreateEntityResponse
     */
    @Test
    public void testEntitymanagerCreateEntityResponse() {
        // TODO: test EntitymanagerCreateEntityResponse
    }

    /**
     * Test the property 'attributeWriteErrors'
     */
    @Test
    public void attributeWriteErrorsTest() {
        // TODO: test attributeWriteErrors
    }

    /**
     * Test the property 'entity'
     */
    @Test
    public void entityTest() {
        // TODO: test entity
    }

}
