/*
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.EntitymanagerAttributeOption;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EntitymanagerGetAttributeOptionResponse
 */
public class EntitymanagerGetAttributeOptionResponseTest {
    private final EntitymanagerGetAttributeOptionResponse model = new EntitymanagerGetAttributeOptionResponse();

    /**
     * Model tests for EntitymanagerGetAttributeOptionResponse
     */
    @Test
    public void testEntitymanagerGetAttributeOptionResponse() {
        // TODO: test EntitymanagerGetAttributeOptionResponse
    }

    /**
     * Test the property 'option'
     */
    @Test
    public void optionTest() {
        // TODO: test option
    }

}
