/*
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.EntitymanagerEntityIdentifier;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EntitymanagerDeleteAttributeRequest
 */
public class EntitymanagerDeleteAttributeRequestTest {
    private final EntitymanagerDeleteAttributeRequest model = new EntitymanagerDeleteAttributeRequest();

    /**
     * Model tests for EntitymanagerDeleteAttributeRequest
     */
    @Test
    public void testEntitymanagerDeleteAttributeRequest() {
        // TODO: test EntitymanagerDeleteAttributeRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'entityData'
     */
    @Test
    public void entityDataTest() {
        // TODO: test entityData
    }

    /**
     * Test the property 'entityId'
     */
    @Test
    public void entityIdTest() {
        // TODO: test entityId
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

}
