/*
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.client.model.EntitymanagerRenderAs;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EntitymanagerUpdateAttributeRequestPayload
 */
public class EntitymanagerUpdateAttributeRequestPayloadTest {
    private final EntitymanagerUpdateAttributeRequestPayload model = new EntitymanagerUpdateAttributeRequestPayload();

    /**
     * Model tests for EntitymanagerUpdateAttributeRequestPayload
     */
    @Test
    public void testEntitymanagerUpdateAttributeRequestPayload() {
        // TODO: test EntitymanagerUpdateAttributeRequestPayload
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property '_default'
     */
    @Test
    public void _defaultTest() {
        // TODO: test _default
    }

    /**
     * Test the property 'sort'
     */
    @Test
    public void sortTest() {
        // TODO: test sort
    }

    /**
     * Test the property 'groupCode'
     */
    @Test
    public void groupCodeTest() {
        // TODO: test groupCode
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'renderAs'
     */
    @Test
    public void renderAsTest() {
        // TODO: test renderAs
    }

}
