/*
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EntitymanagerAttributeOptionSwatch
 */
public class EntitymanagerAttributeOptionSwatchTest {
    private final EntitymanagerAttributeOptionSwatch model = new EntitymanagerAttributeOptionSwatch();

    /**
     * Model tests for EntitymanagerAttributeOptionSwatch
     */
    @Test
    public void testEntitymanagerAttributeOptionSwatch() {
        // TODO: test EntitymanagerAttributeOptionSwatch
    }

    /**
     * Test the property 'grn'
     */
    @Test
    public void grnTest() {
        // TODO: test grn
    }

    /**
     * Test the property 'hex'
     */
    @Test
    public void hexTest() {
        // TODO: test hex
    }

}
