/*
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.EntitymanagerAttributeOption;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EntitymanagerUpdateAttributeOptionsRequest
 */
public class EntitymanagerUpdateAttributeOptionsRequestTest {
    private final EntitymanagerUpdateAttributeOptionsRequest model = new EntitymanagerUpdateAttributeOptionsRequest();

    /**
     * Model tests for EntitymanagerUpdateAttributeOptionsRequest
     */
    @Test
    public void testEntitymanagerUpdateAttributeOptionsRequest() {
        // TODO: test EntitymanagerUpdateAttributeOptionsRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'listCode'
     */
    @Test
    public void listCodeTest() {
        // TODO: test listCode
    }

    /**
     * Test the property 'options'
     */
    @Test
    public void optionsTest() {
        // TODO: test options
    }

}
