/*
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListProductsRequestFilter
 */
public class ListProductsRequestFilterTest {
    private final ListProductsRequestFilter model = new ListProductsRequestFilter();

    /**
     * Model tests for ListProductsRequestFilter
     */
    @Test
    public void testListProductsRequestFilter() {
        // TODO: test ListProductsRequestFilter
    }

    /**
     * Test the property 'createdAtStart'
     */
    @Test
    public void createdAtStartTest() {
        // TODO: test createdAtStart
    }

    /**
     * Test the property 'createdAtEnd'
     */
    @Test
    public void createdAtEndTest() {
        // TODO: test createdAtEnd
    }

    /**
     * Test the property 'updatedAtStart'
     */
    @Test
    public void updatedAtStartTest() {
        // TODO: test updatedAtStart
    }

    /**
     * Test the property 'updatedAtEnd'
     */
    @Test
    public void updatedAtEndTest() {
        // TODO: test updatedAtEnd
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
