/*
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.client.model.ProductFieldMask;
import org.openapitools.client.model.ProtobufAny;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProductBulkUpdateRequestV2Payload
 */
public class ProductBulkUpdateRequestV2PayloadTest {
    private final ProductBulkUpdateRequestV2Payload model = new ProductBulkUpdateRequestV2Payload();

    /**
     * Model tests for ProductBulkUpdateRequestV2Payload
     */
    @Test
    public void testProductBulkUpdateRequestV2Payload() {
        // TODO: test ProductBulkUpdateRequestV2Payload
    }

    /**
     * Test the property 'updateMask'
     */
    @Test
    public void updateMaskTest() {
        // TODO: test updateMask
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

}
