/*
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ProductLocalizedText;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProductAssetsEntryMetadata
 */
public class ProductAssetsEntryMetadataTest {
    private final ProductAssetsEntryMetadata model = new ProductAssetsEntryMetadata();

    /**
     * Model tests for ProductAssetsEntryMetadata
     */
    @Test
    public void testProductAssetsEntryMetadata() {
        // TODO: test ProductAssetsEntryMetadata
    }

    /**
     * Test the property 'roles'
     */
    @Test
    public void rolesTest() {
        // TODO: test roles
    }

    /**
     * Test the property 'alt'
     */
    @Test
    public void altTest() {
        // TODO: test alt
    }

}
