/*
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ProductAttributeResponseError;
import org.openapitools.client.model.ProductProductResponseError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProductUpdateProductResponse
 */
public class ProductUpdateProductResponseTest {
    private final ProductUpdateProductResponse model = new ProductUpdateProductResponse();

    /**
     * Model tests for ProductUpdateProductResponse
     */
    @Test
    public void testProductUpdateProductResponse() {
        // TODO: test ProductUpdateProductResponse
    }

    /**
     * Test the property 'success'
     */
    @Test
    public void successTest() {
        // TODO: test success
    }

    /**
     * Test the property 'productErrors'
     */
    @Test
    public void productErrorsTest() {
        // TODO: test productErrors
    }

    /**
     * Test the property 'attributeErrors'
     */
    @Test
    public void attributeErrorsTest() {
        // TODO: test attributeErrors
    }

}
