/*
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ProductAssetsEntryMetadata;
import org.openapitools.client.model.ProductLocalizedAsset;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProductUpdateAssetEntryPayload
 */
public class ProductUpdateAssetEntryPayloadTest {
    private final ProductUpdateAssetEntryPayload model = new ProductUpdateAssetEntryPayload();

    /**
     * Model tests for ProductUpdateAssetEntryPayload
     */
    @Test
    public void testProductUpdateAssetEntryPayload() {
        // TODO: test ProductUpdateAssetEntryPayload
    }

    /**
     * Test the property 'assetGrn'
     */
    @Test
    public void assetGrnTest() {
        // TODO: test assetGrn
    }

    /**
     * Test the property 'localizedAssetGrn'
     */
    @Test
    public void localizedAssetGrnTest() {
        // TODO: test localizedAssetGrn
    }

    /**
     * Test the property 'position'
     */
    @Test
    public void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

}
