/*
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ProductUpdateAssetEntryPayload;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce_Product.JSON;

/**
 * BulkUpdateAssetsEntriesRequestUpdateEntity
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-29T10:49:30.026307733Z[Etc/UTC]")
public class BulkUpdateAssetsEntriesRequestUpdateEntity {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_PAYLOAD = "payload";
  @SerializedName(SERIALIZED_NAME_PAYLOAD)
  private ProductUpdateAssetEntryPayload payload;

  public static final String SERIALIZED_NAME_PAYLOAD_MASK = "payloadMask";
  @SerializedName(SERIALIZED_NAME_PAYLOAD_MASK)
  private String payloadMask;

  public BulkUpdateAssetsEntriesRequestUpdateEntity() {
  }

  public BulkUpdateAssetsEntriesRequestUpdateEntity id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  public BulkUpdateAssetsEntriesRequestUpdateEntity payload(ProductUpdateAssetEntryPayload payload) {
    this.payload = payload;
    return this;
  }

   /**
   * Get payload
   * @return payload
  **/
  @javax.annotation.Nullable
  public ProductUpdateAssetEntryPayload getPayload() {
    return payload;
  }

  public void setPayload(ProductUpdateAssetEntryPayload payload) {
    this.payload = payload;
  }


  public BulkUpdateAssetsEntriesRequestUpdateEntity payloadMask(String payloadMask) {
    this.payloadMask = payloadMask;
    return this;
  }

   /**
   * Get payloadMask
   * @return payloadMask
  **/
  @javax.annotation.Nullable
  public String getPayloadMask() {
    return payloadMask;
  }

  public void setPayloadMask(String payloadMask) {
    this.payloadMask = payloadMask;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkUpdateAssetsEntriesRequestUpdateEntity bulkUpdateAssetsEntriesRequestUpdateEntity = (BulkUpdateAssetsEntriesRequestUpdateEntity) o;
    return Objects.equals(this.id, bulkUpdateAssetsEntriesRequestUpdateEntity.id) &&
        Objects.equals(this.payload, bulkUpdateAssetsEntriesRequestUpdateEntity.payload) &&
        Objects.equals(this.payloadMask, bulkUpdateAssetsEntriesRequestUpdateEntity.payloadMask);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, payload, payloadMask);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkUpdateAssetsEntriesRequestUpdateEntity {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("    payloadMask: ").append(toIndentedString(payloadMask)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("payload");
    openapiFields.add("payloadMask");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to BulkUpdateAssetsEntriesRequestUpdateEntity
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BulkUpdateAssetsEntriesRequestUpdateEntity.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BulkUpdateAssetsEntriesRequestUpdateEntity is not found in the empty JSON string", BulkUpdateAssetsEntriesRequestUpdateEntity.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BulkUpdateAssetsEntriesRequestUpdateEntity.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BulkUpdateAssetsEntriesRequestUpdateEntity` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      // validate the optional field `payload`
      if (jsonObj.get("payload") != null && !jsonObj.get("payload").isJsonNull()) {
        ProductUpdateAssetEntryPayload.validateJsonElement(jsonObj.get("payload"));
      }
      if ((jsonObj.get("payloadMask") != null && !jsonObj.get("payloadMask").isJsonNull()) && !jsonObj.get("payloadMask").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `payloadMask` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payloadMask").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BulkUpdateAssetsEntriesRequestUpdateEntity.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BulkUpdateAssetsEntriesRequestUpdateEntity' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BulkUpdateAssetsEntriesRequestUpdateEntity> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BulkUpdateAssetsEntriesRequestUpdateEntity.class));

       return (TypeAdapter<T>) new TypeAdapter<BulkUpdateAssetsEntriesRequestUpdateEntity>() {
           @Override
           public void write(JsonWriter out, BulkUpdateAssetsEntriesRequestUpdateEntity value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BulkUpdateAssetsEntriesRequestUpdateEntity read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BulkUpdateAssetsEntriesRequestUpdateEntity given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BulkUpdateAssetsEntriesRequestUpdateEntity
  * @throws IOException if the JSON string is invalid with respect to BulkUpdateAssetsEntriesRequestUpdateEntity
  */
  public static BulkUpdateAssetsEntriesRequestUpdateEntity fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BulkUpdateAssetsEntriesRequestUpdateEntity.class);
  }

 /**
  * Convert an instance of BulkUpdateAssetsEntriesRequestUpdateEntity to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

