/*
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets entitymanagerRenderAs
 */
@JsonAdapter(EntitymanagerRenderAs.Adapter.class)
public enum EntitymanagerRenderAs {
  
  DEFAULT("DEFAULT"),
  
  WYSIWYG("WYSIWYG");

  private String value;

  EntitymanagerRenderAs(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EntitymanagerRenderAs fromValue(String value) {
    for (EntitymanagerRenderAs b : EntitymanagerRenderAs.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<EntitymanagerRenderAs> {
    @Override
    public void write(final JsonWriter jsonWriter, final EntitymanagerRenderAs enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EntitymanagerRenderAs read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EntitymanagerRenderAs.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    EntitymanagerRenderAs.fromValue(value);
  }
}

