/*
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.EntitymanagerAttributeWriteErrors;
import org.openapitools.client.model.EntitymanagerEntity;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce_Product.JSON;

/**
 * EntitymanagerCreateEntityResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-29T10:49:30.026307733Z[Etc/UTC]")
public class EntitymanagerCreateEntityResponse {
  public static final String SERIALIZED_NAME_ATTRIBUTE_WRITE_ERRORS = "attributeWriteErrors";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTE_WRITE_ERRORS)
  private EntitymanagerAttributeWriteErrors attributeWriteErrors;

  public static final String SERIALIZED_NAME_ENTITY = "entity";
  @SerializedName(SERIALIZED_NAME_ENTITY)
  private EntitymanagerEntity entity;

  public EntitymanagerCreateEntityResponse() {
  }

  public EntitymanagerCreateEntityResponse attributeWriteErrors(EntitymanagerAttributeWriteErrors attributeWriteErrors) {
    this.attributeWriteErrors = attributeWriteErrors;
    return this;
  }

   /**
   * Get attributeWriteErrors
   * @return attributeWriteErrors
  **/
  @javax.annotation.Nullable
  public EntitymanagerAttributeWriteErrors getAttributeWriteErrors() {
    return attributeWriteErrors;
  }

  public void setAttributeWriteErrors(EntitymanagerAttributeWriteErrors attributeWriteErrors) {
    this.attributeWriteErrors = attributeWriteErrors;
  }


  public EntitymanagerCreateEntityResponse entity(EntitymanagerEntity entity) {
    this.entity = entity;
    return this;
  }

   /**
   * Get entity
   * @return entity
  **/
  @javax.annotation.Nullable
  public EntitymanagerEntity getEntity() {
    return entity;
  }

  public void setEntity(EntitymanagerEntity entity) {
    this.entity = entity;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntitymanagerCreateEntityResponse entitymanagerCreateEntityResponse = (EntitymanagerCreateEntityResponse) o;
    return Objects.equals(this.attributeWriteErrors, entitymanagerCreateEntityResponse.attributeWriteErrors) &&
        Objects.equals(this.entity, entitymanagerCreateEntityResponse.entity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributeWriteErrors, entity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntitymanagerCreateEntityResponse {\n");
    sb.append("    attributeWriteErrors: ").append(toIndentedString(attributeWriteErrors)).append("\n");
    sb.append("    entity: ").append(toIndentedString(entity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("attributeWriteErrors");
    openapiFields.add("entity");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to EntitymanagerCreateEntityResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EntitymanagerCreateEntityResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EntitymanagerCreateEntityResponse is not found in the empty JSON string", EntitymanagerCreateEntityResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EntitymanagerCreateEntityResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EntitymanagerCreateEntityResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `attributeWriteErrors`
      if (jsonObj.get("attributeWriteErrors") != null && !jsonObj.get("attributeWriteErrors").isJsonNull()) {
        EntitymanagerAttributeWriteErrors.validateJsonElement(jsonObj.get("attributeWriteErrors"));
      }
      // validate the optional field `entity`
      if (jsonObj.get("entity") != null && !jsonObj.get("entity").isJsonNull()) {
        EntitymanagerEntity.validateJsonElement(jsonObj.get("entity"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EntitymanagerCreateEntityResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EntitymanagerCreateEntityResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EntitymanagerCreateEntityResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EntitymanagerCreateEntityResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<EntitymanagerCreateEntityResponse>() {
           @Override
           public void write(JsonWriter out, EntitymanagerCreateEntityResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EntitymanagerCreateEntityResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EntitymanagerCreateEntityResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EntitymanagerCreateEntityResponse
  * @throws IOException if the JSON string is invalid with respect to EntitymanagerCreateEntityResponse
  */
  public static EntitymanagerCreateEntityResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EntitymanagerCreateEntityResponse.class);
  }

 /**
  * Convert an instance of EntitymanagerCreateEntityResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

