/*
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ProductMediaGalleryEntry;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce_Product.JSON;

/**
 * ProductAddMediaGalleryEntryResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-29T10:49:30.026307733Z[Etc/UTC]")
public class ProductAddMediaGalleryEntryResponse {
  public static final String SERIALIZED_NAME_MEDIA_GALLERY_ENTRY = "mediaGalleryEntry";
  @SerializedName(SERIALIZED_NAME_MEDIA_GALLERY_ENTRY)
  private ProductMediaGalleryEntry mediaGalleryEntry;

  public ProductAddMediaGalleryEntryResponse() {
  }

  public ProductAddMediaGalleryEntryResponse mediaGalleryEntry(ProductMediaGalleryEntry mediaGalleryEntry) {
    this.mediaGalleryEntry = mediaGalleryEntry;
    return this;
  }

   /**
   * Get mediaGalleryEntry
   * @return mediaGalleryEntry
  **/
  @javax.annotation.Nullable
  public ProductMediaGalleryEntry getMediaGalleryEntry() {
    return mediaGalleryEntry;
  }

  public void setMediaGalleryEntry(ProductMediaGalleryEntry mediaGalleryEntry) {
    this.mediaGalleryEntry = mediaGalleryEntry;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductAddMediaGalleryEntryResponse productAddMediaGalleryEntryResponse = (ProductAddMediaGalleryEntryResponse) o;
    return Objects.equals(this.mediaGalleryEntry, productAddMediaGalleryEntryResponse.mediaGalleryEntry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mediaGalleryEntry);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductAddMediaGalleryEntryResponse {\n");
    sb.append("    mediaGalleryEntry: ").append(toIndentedString(mediaGalleryEntry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("mediaGalleryEntry");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ProductAddMediaGalleryEntryResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ProductAddMediaGalleryEntryResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ProductAddMediaGalleryEntryResponse is not found in the empty JSON string", ProductAddMediaGalleryEntryResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ProductAddMediaGalleryEntryResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ProductAddMediaGalleryEntryResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `mediaGalleryEntry`
      if (jsonObj.get("mediaGalleryEntry") != null && !jsonObj.get("mediaGalleryEntry").isJsonNull()) {
        ProductMediaGalleryEntry.validateJsonElement(jsonObj.get("mediaGalleryEntry"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProductAddMediaGalleryEntryResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProductAddMediaGalleryEntryResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProductAddMediaGalleryEntryResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProductAddMediaGalleryEntryResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ProductAddMediaGalleryEntryResponse>() {
           @Override
           public void write(JsonWriter out, ProductAddMediaGalleryEntryResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ProductAddMediaGalleryEntryResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ProductAddMediaGalleryEntryResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ProductAddMediaGalleryEntryResponse
  * @throws IOException if the JSON string is invalid with respect to ProductAddMediaGalleryEntryResponse
  */
  public static ProductAddMediaGalleryEntryResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProductAddMediaGalleryEntryResponse.class);
  }

 /**
  * Convert an instance of ProductAddMediaGalleryEntryResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

