/*
 * Product Service
 * API for managing products
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ProductBulkUpdateResponseResponse;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce_Product.JSON;

/**
 * ProductBulkUpdateResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-29T10:49:30.026307733Z[Etc/UTC]")
public class ProductBulkUpdateResponse {
  public static final String SERIALIZED_NAME_PRODUCT_RESPONSE = "productResponse";
  @SerializedName(SERIALIZED_NAME_PRODUCT_RESPONSE)
  private List<ProductBulkUpdateResponseResponse> productResponse;

  public ProductBulkUpdateResponse() {
  }

  public ProductBulkUpdateResponse productResponse(List<ProductBulkUpdateResponseResponse> productResponse) {
    this.productResponse = productResponse;
    return this;
  }

  public ProductBulkUpdateResponse addProductResponseItem(ProductBulkUpdateResponseResponse productResponseItem) {
    if (this.productResponse == null) {
      this.productResponse = new ArrayList<>();
    }
    this.productResponse.add(productResponseItem);
    return this;
  }

   /**
   * Get productResponse
   * @return productResponse
  **/
  @javax.annotation.Nullable
  public List<ProductBulkUpdateResponseResponse> getProductResponse() {
    return productResponse;
  }

  public void setProductResponse(List<ProductBulkUpdateResponseResponse> productResponse) {
    this.productResponse = productResponse;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductBulkUpdateResponse productBulkUpdateResponse = (ProductBulkUpdateResponse) o;
    return Objects.equals(this.productResponse, productBulkUpdateResponse.productResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productResponse);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductBulkUpdateResponse {\n");
    sb.append("    productResponse: ").append(toIndentedString(productResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("productResponse");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ProductBulkUpdateResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ProductBulkUpdateResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ProductBulkUpdateResponse is not found in the empty JSON string", ProductBulkUpdateResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ProductBulkUpdateResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ProductBulkUpdateResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("productResponse") != null && !jsonObj.get("productResponse").isJsonNull()) {
        JsonArray jsonArrayproductResponse = jsonObj.getAsJsonArray("productResponse");
        if (jsonArrayproductResponse != null) {
          // ensure the json data is an array
          if (!jsonObj.get("productResponse").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `productResponse` to be an array in the JSON string but got `%s`", jsonObj.get("productResponse").toString()));
          }

          // validate the optional field `productResponse` (array)
          for (int i = 0; i < jsonArrayproductResponse.size(); i++) {
            ProductBulkUpdateResponseResponse.validateJsonElement(jsonArrayproductResponse.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProductBulkUpdateResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProductBulkUpdateResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProductBulkUpdateResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProductBulkUpdateResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ProductBulkUpdateResponse>() {
           @Override
           public void write(JsonWriter out, ProductBulkUpdateResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ProductBulkUpdateResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ProductBulkUpdateResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ProductBulkUpdateResponse
  * @throws IOException if the JSON string is invalid with respect to ProductBulkUpdateResponse
  */
  public static ProductBulkUpdateResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProductBulkUpdateResponse.class);
  }

 /**
  * Convert an instance of ProductBulkUpdateResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

